--------------------------------------------------------
--  File created - Thursday-December-01-2016   
--------------------------------------------------------

-- USER SQL
CREATE USER demo IDENTIFIED BY "1234" ;

-- QUOTAS

-- ROLES
GRANT "DBA" TO demo ;

-- SYSTEM PRIVILEGES



--------------------------------------------------------
--  DDL for Table WORLD
--------------------------------------------------------

  CREATE TABLE "DEMO"."WORLD" 
   (	"COUNTRY" VARCHAR2(100 BYTE), 
	"CAPITAL" VARCHAR2(100 BYTE), 
	"POPULATION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DEMO.WORLD
SET DEFINE OFF;
Insert into DEMO.WORLD (COUNTRY,CAPITAL,POPULATION) values ('Afghanistan','Kabul',53000293);
Insert into DEMO.WORLD (COUNTRY,CAPITAL,POPULATION) values ('Belgium','Brussels',10290123);
--------------------------------------------------------
--  DDL for Index WORLD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEMO"."WORLD_PK" ON "DEMO"."WORLD" ("COUNTRY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table WORLD
--------------------------------------------------------

  ALTER TABLE "DEMO"."WORLD" ADD CONSTRAINT "WORLD_PK" PRIMARY KEY ("COUNTRY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DEMO"."WORLD" MODIFY ("POPULATION" NOT NULL ENABLE);
  ALTER TABLE "DEMO"."WORLD" MODIFY ("COUNTRY" NOT NULL ENABLE);
